---
- include_role:
    name: base
    
- name: Wait for swarm token to be created/committed to repo
  command: "curl -o - -Ii --silent https://github.com/bmquiroz/hosts/blob/master/worker_conf"
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 60
  delay: 1
  changed_when: false
  
- git:
    repo: https://github.com/bmquiroz/hosts.git
    dest: /tmp/repo
    
- name: Join swarm cluster as a worker
  command: sudo docker swarm join --token "{{ worker_token }}" --advertise-addr "{{ management_int }}":2377 --data-path-addr "{{ services_int }}" "{{ master_ip }}":2377
  register: worker
 
- name: Show results
  debug: var=worker.stdout
 
- name: Show errors
  debug: var=worker.stderr

- name: Checkout host file
  git: src=https://github.com/bmquiroz/hosts.git dest=/inventory/hosts
  # sudo_user: <your user that has the ssh key>
  
- name: Update host file
  command: "{{item}}"
  with_items:
    - git add .
    - git -c user.name='Boris Quiroz' -c user.email='bmquiroz@email.com' commit -m 'Test1'
    - git remote set-url origin https://bmquiroz:Blowthis1@github.com/bmquiroz/hosts.git
    - git push -u origin master
  args:
    chdir: /inventory/hosts
    
# TO-DO: Loop through Jinja2 tmplate to read volume names/IP addresses to mount
- name: Add EFS mounts based on environment
  command: "{{item}}"
  with_items:
    - sudo docker volume create --driver local --opt type=nfs4 --opt o=addr=10.0.1.109,rw --opt device=:/ --name app1-volume-qa
    - sudo docker volume create --driver local --opt type=nfs4 --opt o=addr=10.0.2.109,rw --opt device=:/ --name app2-volume-qa
  when: lifecycle == "qa"
